### ISSUE TITLE
Question about this implementation

### ISSUE THREAD

**Issue by indiketa** [tsegismont/vertx-contextual-logging#1]
The vertx context is shared with all handlers or is created a new context (localContext) on each handler execution? The vertx documentation is not clear in this aspect. 

Your approach will save a lot of lines in our development.

Many thanks!

**Comment by tsegismont** [comment]
@indiketa sorry I missed your comment... The `localContext` method is new in Vert.x 4.0 with the tracing SPI.

The RFC: https://github.com/vert-x3/wiki/wiki/RFC:-context-tracing

I have planned to create a lib out of this. It should be released soon.

**Comment by u6f6o** [comment]
@tsegismont : Do you have any news on this lib?

**Comment by tsegismont** [comment]
@u6f6o the library has been released, you can find information about how to use it in the README file.
