### ISSUE TITLE
ContextualData should use slf4j LoggerFactory and Logger

### ISSUE THREAD

**Issue by jebl01** [tsegismont/vertx-contextual-logging#8]
Not sure, but it might be because I miss a dependency or is on an other version of VertX (3.6.3), but I don't have the Vertx LoggerFactory or Logger on my classpath which gives a deadlock at startup (class not found exception).
By changing to the slf4j ones, everything works as expected :-)

**Comment by tsegismont** [comment]
This library works with Vert.x 4 only: https://github.com/tsegismont/vertx-contextual-logging#how-it-works

**Comment by jebl01** [comment]
👍
